# deploy.yml

- name: Deploy to EC2
  hosts: all
  become: true
  tasks:
    - name: Copy JAR file to EC2
      ansible.builtin.copy:
        src: "target/totalcarefix-0.0.1-SNAPSHOT.jar"
        dest: "/home/ec2-user/totalcarefix-0.0.1-SNAPSHOT.jar"
        remote_src: yes

    - name: Stop existing TotalCareFix service
      ansible.builtin.systemd:
        name: totalcarefix-app
        state: stopped
        enabled: no

    - name: Move JAR file to installation directory
      ansible.builtin.shell: mv /home/ec2-user/totalcarefix-0.0.1-SNAPSHOT.jar /opt/demo/

    - name: Start TotalCareFix service
      ansible.builtin.systemd:
        name: totalcarefix-app
        state: started
        enabled: yes
