name: Java CI/CD with Maven and Deploy to EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: |
        mvn clean install
        mkdir artifacts && cp target/*.jar artifacts
        cd artifacts && ls

    - name: Save artifact
      uses: actions/upload-artifact@v2
      with:
        name: github-action-artifact
        path: artifacts

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: 34.242.206.146
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo systemctl stop totalcarefix-app
          mv /home/ec2-user/totalcarefix-0.0.1-SNAPSHOT.jar /opt/demo/
          sudo systemctl start totalcarefix-app
